version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: charlie-app
    ports:
      - 8084:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - redis
      - mailhog
    environment:
      DB_HOST: mysql
      DB_DATABASE: charlie_app
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
      REDIS_CLIENT: predis
      QUEUE_CONNECTION: redis
    networks:
      - app-net

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - app-db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: charlie_app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-net

  redis:
    image: redis:5.0.8-alpine
    ports:
      - 16379:6379
    networks:
      - app-net

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8026:8025
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  app-db-data: {}
